# Generated by Django 4.2.3 on 2023-09-28 20:36

import Eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0005_evento_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to=Eventos.models.get_upload_path_evento),
        ),
    ]
