# Generated by Django 4.2.3 on 2023-09-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0006_alter_evento_foto_principal'),
        ('Eventos', 'add_evento_modelo'),
    ]

    operations = [
    ]
