# Generated by Django 4.2.3 on 2023-09-28 20:36

import Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_remove_user_foto_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=Usuarios.models.get_upload_path_usuario),
        ),
    ]
